# Generated by Django 2.2.3 on 2019-07-26 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('publish_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('picture', models.ImageField(upload_to='pics')),
                ('about', models.TextField()),
                ('location', models.TextField()),
                ('duration', models.TextField()),
            ],
        ),
    ]
