# Generated by Django 2.2.3 on 2019-07-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ware',
            old_name='name',
            new_name='name_ware',
        ),
        migrations.RemoveField(
            model_name='ware',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='ware',
            name='author',
        ),
        migrations.RemoveField(
            model_name='ware',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='ware',
            name='seller',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
