# Generated by Django 2.2.3 on 2019-07-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter_app', '0002_auto_20190728_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ware',
            old_name='seller',
            new_name='contact_info',
        ),
        migrations.AddField(
            model_name='ware',
            name='insurance',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ware',
            name='price',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ware',
            name='duration',
            field=models.TimeField(),
        ),
    ]
