# Generated by Django 2.2.3 on 2019-07-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter_app', '0003_auto_20190729_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='insurance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ware',
            name='price',
            field=models.IntegerField(),
        ),
    ]
