# Generated by Django 2.2.3 on 2019-07-30 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('renter_app', '0004_auto_20190729_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='duration',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ware',
            name='insurance',
            field=models.IntegerField(help_text='hint:insurance non refundable'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
